FROM node:20-slim

# Set the working directory
WORKDIR /opt/app

# Copy package.json and package-lock.json
COPY package.json ./
COPY package.lock.json ./
RUN npm i

# Copy the rest of the application code
COPY ./bin ./bin
COPY ./src ./src
COPY ./eslintrc.js ./
COPY ./tsconfig.json ./
COPY ./.eslintignore ./
COPY ./.prettierignore ./
COPY ./.prettierrc ./

# Start the application
CMD [ "npm", "start" ]