FROM node:20-slim

# Set the working directory
WORKDIR /opt/app

# Required for prisma to run
RUN apt-get update && apt-get install -y openssl


# Copy package.json and package-lock.json
COPY package.json ./
COPY package-lock.json ./package-lock.json
RUN npm i

COPY ./prisma ./prisma
RUN npm run prisma:gen


# Copy the rest of the application code
COPY ./bin ./bin
COPY ./src ./src
COPY ./tsconfig.json ./tsconfig.json


# Start the application
CMD [ "npm", "start" ]