name: CI/CD Pipeline

on:
  push:
    branches:
        main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  CI: true
  DATABASE_PASSWORD: randompassword
  DATABASE_NAME: testdb
  DATABASE_URL: postgresql://postgres:testpassword@localhost:5433/testdb
  APP_PORT: 8000
  CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
  CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
  CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
  CLOUDINARY_UPLOAD_PRESET: ml_default
  CLOUDINARY_FOLDER: unit-test

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [unit-tests, integration-tests, linters]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Make sure docker-compose is installed
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - name: Install dependencies
        run: npm install

      - name: Install ariga/atlas-go
        uses: ariga/setup-atlas@v0

      - name: Run ${{ matrix.job }}
        run: |
          # Run Linters
          if [ "${{ matrix.job }}" == "linters" ]; then
            npm run lint

          # Run Unit Tests
          elif [ "${{ matrix.job }}" == "unit-tests" ]; then
            npm run test:cov

          # Run Integration Tests
          elif [ "${{ matrix.job }}" == "integration-tests" ]; then
            npm run inttest:cov
          fi

      - name: Upload coverage reports
        if: ${{ matrix.job == 'unit-tests' }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-reports
          path: coverage/*

      - name: Upload integration coverage reports
        if: ${{ matrix.job == 'integration-tests' }}
        uses: actions/upload-artifact@v2
        with:
          name: integration-coverage-reports
          path: coverage-integration/*

  deploy-coverage-report:
    name: Deploy Coverage Report
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install -y curl
    
      - name: Download coverage reports
        uses: actions/download-artifact@v2
        with:
            name: coverage-reports
            path: coverage

      - name: Deploy coverage reports to Cloudinary
        run: |
            #!/bin/bash

            # Directory containing the Jest coverage report
            COVERAGE_DIR="coverage"
            CLOUDINARY_FOLDER="coverage_report"

            # Function to upload a file to Cloudinary
            upload_file() {
            local file_path=$1
            local cloudinary_folder=$2

            response=$(curl -s -X POST "https://api.cloudinary.com/v1_1/$CLOUDINARY_CLOUD_NAME/auto/upload" \
                -H "Content-Type: multipart/form-data" \
                -F "file=@$file_path" \
                -F "folder=$cloudinary_folder" \
                -F "api_key=$CLOUDINARY_API_KEY" \
                -F "timestamp=$(date +%s)" \
                -F "signature=$(echo -n "folder=$cloudinary_folder&timestamp=$(date +%s)$CLOUDINARY_API_SECRET" | sha1sum | awk '{print $1}')" )

            echo "Uploaded $file_path to $cloudinary_folder"
            }

            # Function to recursively upload all files in a directory
            upload_directory() {
            local dir=$1
            local cloudinary_folder=$2

            for file in "$dir"/*; do
                if [[ -d $file ]]; then
                upload_directory "$file" "$cloudinary_folder/$(basename "$file")"
                else
                upload_file "$file" "$cloudinary_folder"
                fi
            done
            }

            # Upload the coverage directory
            upload_directory "$COVERAGE_DIR" "$CLOUDINARY_FOLDER"

            echo "All files uploaded successfully!"