name: CI/CD Pipeline

on:
  push:
    tags:
      - '*'

env:
  CI: true
  DATABASE_PASSWORD: randompassword
  DATABASE_NAME: testdb
  DATABASE_URL: postgresql://postgres:testpassword@localhost:5433/testdb
  APP_PORT: 8000

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [unit-tests, integration-tests, linters]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Make sure docker-compose is installed
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - name: Install dependencies
        run: npm install

      - name: Install ariga/atlas-go
        uses: ariga/setup-atlas@v0

      - name: Run ${{ matrix.job }}
        run: |
          # Run Linters
          if [ "${{ matrix.job }}" == "linters" ]; then
            npm run lint

          # Run Unit Tests
          elif [ "${{ matrix.job }}" == "unit-tests" ]; then
            npm run test:cov

          # Run Integration Tests
          elif [ "${{ matrix.job }}" == "integration-tests" ]; then
            npm run inttest:cov

      - name: Upload coverage reports
        if: ${{ matrix.job == 'unit-tests' }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-reports
          path: coverage/*

      - name: Upload integration coverage reports
        if: ${{ matrix.job == 'integration-tests' }}
        uses: actions/upload-artifact@v2
        with:
          name: integration-coverage-reports
          path: coverage-integration/*

  deploy-unit-coverage:
    name: Deploy Unit Test Coverage
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download coverage reports
        uses: actions/download-artifact@v2
        with:
          name: coverage-reports
          path: coverage

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: coverage/lcov-report
          publish_branch: gh-pages
          dest_dir: unit-tests
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Jest unit test coverage for tag ${{ github.ref_name }}'

  deploy-integration-coverage:
    name: Deploy Integration Test Coverage
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download integration coverage reports
        uses: actions/download-artifact@v2
        with:
          name: integration-coverage-reports
          path: coverage-integration

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: coverage-integration/lcov-report
          publish_branch: gh-pages
          dest_dir: integration-tests
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Jest integration test coverage for tag ${{ github.ref_name }}'
