name: Integration Tests

on:
  workflow_run:
    workflows: ["Checkout and Setup"]
    types:
      - completed

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules

      - name: Run integration tests
        run: npm run inttest
