name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  checkout-setup:
    name: Checkout Code
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: ['20']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
                
  node-setup:
    name: Setup Node Version
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
  
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
        
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: npm run test
